
set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'vim-syntastic/syntastic'
Plugin 'nvie/vim-flake8'
"git support
Plugin 'tpope/vim-fugitive'


" add all your plugins here (note older versions of Vundle
" used Bundle instead of Plugin)

" ...

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" PEP 8 indentation
set tabstop=4
set softtabstop=4
set shiftwidth=4
set textwidth=79
set expandtab
set autoindent
set fileformat=unix
set nu

" UTF-8 support
set encoding=utf-8

let python_highlight_all=1
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_error_symbol = "✗"

syntax on

"set makeprg=pylint\ --reports=n\ --output-format=parseable\ %:p
"set errorformat=%f:%l:\ %m

:cnoremap lt  SyntasticCheck
:cnoremap ln  lnext

setlocal spell "spellang=en
hi clear SpellBad
hi SpellBad cterm=underline ctermfg=red
set spellfile=~/.vim/spell/techspeak.utf-8.add

